### ISSUE TITLE
[1.0] Todo list

### ISSUE THREAD

**Issue by tgallice** [tgallice/fb-messenger-sdk#10]
- [ ] Add Airline template
- [ ] Add Sender actions
- [ ] Handle Account linking
- [ ] Handle webhook ?
- [ ] Apply php-cs-fixer

**Comment by eight-buddha** [comment]
handle webhook please !

**Comment by savchuks** [comment]
do you have in plans to add [Link Account](https://developers.facebook.com/docs/messenger-platform/account-linking/link-account) ?

**Comment by Ismael-sm** [comment]
Hi, can you add how to send quickReplies in the documentation please?

```
$message = new FBMessenger\Model\Message(<QUICK_REPLIES_TITLE_TEXT>);
$message->setQuickReplies([
    new Model\QuickReply('Option1', 'YOUR_PAYLOAD_HERE'),
    new Model\QuickReply('Option2', 'YOUR_PAYLOAD_HERE')
]);
$this->messenger->sendMessage(<USER_ID>, $message);
```

**Comment by Ismael-sm** [comment]
Something i thing is a bug is that when i click on a QuciReply i receive it as a message_event and not as a postback_event, because i need to is_null($event->getMessage()->getQuickReply()) instean of just receiving it as a postback_event

**Comment by tgallice** [comment]
Hello @Ismael-sm thank for the feedback. You right, I will add it in the doc. 
For the QuickReply event, it's not a bug. [Cf. to the documentation](https://developers.facebook.com/docs/messenger-platform/send-api-reference/quick-replies), when you click on a quick reply this send back a message event. A quick reply is not only a posback. It's return the text too and a Location can be set as an attachment if the quick reply content-type is define as `location`. 

But I will add some methods as shortcut in the MessageEvent:
- `MessageEvent::isQuickReply() : bool`
- `MessageEvent::getQuickReplyPayload() : null|string`
- `MessageEvent::isLocation() : bool`
- `MessageEvent::getLocation() : null|array`

This seem good to you ?

**Comment by Ismael-sm** [comment]
Yes and your fast response is apreciated. I not sure if this is the rigth way to do this, but i created a "MessengerController" class which have a function called processUpdate($webookHandler->getAllCallbackEvents()); and in this function i have this

```
foreach ($events as $event) {
            /**
             * https://developers.facebook.com/docs/messenger-platform/webhook-reference#setup
             */
            switch ($event->getType()) {
                case 'message_event':
                    $this->processMessage($event);
                    break;
                case 'message_read_event':
                    break;
                case 'message_delivery_event';
                    break;
                case 'message_echo_event';
                    break;
                case 'authentication_event':
                    break;
                case 'account_linking_event':
                    $this->processAccountLinking($event);
                    break;
                case 'postback_event';
                    $this->processPostback($event);
                    break;
                case 'raw_event';
                    break;
            }
        }
```

You maybe can implement some kind of handler that invokes a function dependent of the type of the event.

Like

```
$messenger->onMessage(...);
$messenger->onPostback(...);
```

etc or you can manage the postsbacks as "commands"

`$messenger->addCommand/postbackHandler(<CLASS>);`

But well that is just ideas, you are the programmer ;)

**Comment by tgallice** [comment]
:+1:  Yes this is a good idea ! This will give more flexibility. Feel free to open a PR/issue to implement/speak about this feature.

**Comment by kormid** [comment]
@tgallice I really don't know how this git think works, it says i don't have permission to push when i click to Sync, and i see mine commits in the app, but cannot see them here in the website? :s

**Comment by tgallice** [comment]
Have you fork this repo first ? Please look to the github doc : https://guides.github.com/activities/contributing-to-open-source/

**Comment by kormid** [comment]
Thank's @tgallice, i made the pull request now ^^

**Comment by Giambapisasale** [comment]
TODO list:
can you add the send API endpoint and is_reusable field on attachments?

[send API reference](https://developers.facebook.com/docs/messenger-platform/send-api-reference/attachment-upload)

thanks!
